openapi: 3.0.3
info:
  title: mcs_ver2
  version: 1.0.0
paths:
  /api/home:
    $ref: './paths/api/home/index.yml'
  /api/spotlight:
    $ref: './paths/api/spotlight/index.yml'
  /v1/api/books/bestseller:
    $ref: './paths/api/book/bestseller.yml'
  /v1/api/books:
    $ref: './paths/api/book/index.yml'
